import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-8 o-container">
        <div className="o-row ">
          <div className=" o-col-xxs-4 o-col-md-1">
            <div
              style={{
                height: '280px',
                backgroundColor: '#ccc',
              }}
            />
          </div>

          <div className=" o-col-xxs-4 o-col-md-2">
            <div
              style={{
                height: '280px',
                backgroundColor: '#ccc',
              }}
            />
          </div>

          <div className=" o-col-xxs-4 o-col-md-14">
            <div
              style={{
                height: '280px',
                backgroundColor: 'aqua',
              }}
            >
              Custom column padding
            </div>
          </div>

          <div className=" o-col-xxs-4 o-col-sm-7">
            <div
              style={{
                height: '280px',
                backgroundColor: 'red',
              }}
            >
              Custom column padding
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
/* The `@mixin make-cssgrid` is a mixin that generates CSS Grid classes for a given number of columns
and breakpoints. It loops through each breakpoint defined in `` and generates classes
for that breakpoint. */
